name: Cache Dependencies Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Prime cache 1148dc9
        id: prime-cache-1148dc9
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: cache-1148dc9
          restore-keys: |
            cache-1148dc9
          
      - name: Echo cache hit/miss
        run: |
          if [ "${{ steps.prime-cache-1148dc9.outputs.cache-hit }}" == "true" ]; then
            echo "Cache hit!"
          else
            echo "Cache miss!"
          fi

      - name: Install dependencies
        run: npm install
